# Unique name for this workflow
name: Deploy integration branch to integration and staging/uat orgs

# Definition when the workflow should run
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# Jobs to be executed
jobs:
    deploy-branch-to-int:
        runs-on: ubuntu-latest
        steps:
          - uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL_INTA }}

          # - name: sfdx-test-run
          #   run: sfdx force:apex:test:run -l RunLocalTests -w 30
              
